/**
 * Utility functions for generating consistent restaurant IDs
 */

/**
 * Simple hash function to generate a consistent numeric hash from a string
 */
function simpleHash(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
        const char = str.charCodeAt(i);
        hash = ((hash << 5) - hash) + char;
        hash = hash & hash; // Convert to 32-bit integer
    }
    return Math.abs(hash);
}

/**
 * Sanitize a string to be URL-safe and Firebase-compatible
 * Removes special characters, converts to lowercase, replaces spaces with underscores
 */
function sanitizeName(name: string): string {
    return name
        .toLowerCase()
        .trim()
        // Remove all non-alphanumeric characters except spaces
        .replace(/[^a-z0-9\s]/g, '')
        // Replace multiple spaces with single space
        .replace(/\s+/g, ' ')
        // Replace spaces with underscores
        .replace(/\s/g, '_')
        // Limit to first 30 characters
        .substring(0, 30)
        // Remove trailing underscores
        .replace(/_+$/, '');
}

/**
 * Generate a unique, deterministic restaurant ID from a restaurant name
 * 
 * @param name - The restaurant name
 * @returns A unique ID in format: rest_{sanitized_name}_{hash}
 * 
 * @example
 * generateRestaurantId("Cha Ting 華華") // => "rest_cha_ting_3a7f9b"
 * generateRestaurantId("Joe's Pizza & Pasta") // => "rest_joes_pizza_pasta_1c2d3e"
 */
export function generateRestaurantId(name: string): string {
    const sanitized = sanitizeName(name);
    const hash = simpleHash(name);
    const hashHex = hash.toString(16).substring(0, 6);

    // If sanitization resulted in empty string, use hash only
    if (!sanitized) {
        return `rest_${hashHex}`;
    }

    return `rest_${sanitized}_${hashHex}`;
}

/**
 * Check if a string is a valid restaurant ID (generated by this utility)
 */
export function isValidRestaurantId(id: string): boolean {
    return /^rest_[a-z0-9_]+_[a-f0-9]{1,6}$/.test(id) || /^rest_[a-f0-9]{1,6}$/.test(id);
}
